### ISSUE TITLE
cannot craft the right kind of salt easily

### ISSUE THREAD

**Issue by JugglerMaster** [maxlowry123/maxFTBcraft#11]
I needed the craft a heat cable from Magneticraft which uses a salt block. the compressed salt is the default recipe and that doesn't work. Used a normal crafting table to select which kind I wanted and boom, was good.

**Comment by JugglerMaster** [comment]
I will also add that this was with pam's harvestcraft salt so it might not be anything.

**Comment by maxlowry123** [comment]
It seems like it is not possible to fix this.
